# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: "3.8"
services:
 
  ## Apache Tika Server 
  tika:
    image: apache/tika-grpc:latest-full
    command: -c /tika-config.xml
    restart: on-failure
    ports:
      - "50052:50052"

    volumes:
      # Replace the below with the configuration you want to use, or with your own custom one 
      # -  ./sample-configs/vision/inception-rest.xml:/tika-config.xml
      # -  ./sample-configs/vision/inception-rest-video.xml:/tika-config.xml
      -  ./sample-configs/vision/inception-rest-caption.xml:/tika-config.xml
   
    depends_on:
      # You can comment out any you don't need here and in the Vision Service section below
      - inception-rest
      - inception-caption
      - inception-video

  ## Vision Services 
  inception-rest:
    build: https://raw.githubusercontent.com/dameikle/tika-dockers/patch-1/InceptionRestDockerfile
    ports:
      - "8764:8764"

  inception-caption:
    build: https://raw.githubusercontent.com/dameikle/tika-dockers/patch-1/Im2txtRestDockerfile
    ports:
      - "8765:8764"

  inception-video:
    build: https://raw.githubusercontent.com/dameikle/tika-dockers/patch-1/InceptionVideoRestDockerfile
    ports:
      - "8766:8764"

